### ISSUE TITLE
Create two equally sized towns

### ISSUE THREAD

**Issue by msteiger** [Terasology/Cities#4]
##

**Comment by jdrueckert** [comment]
@Cervator Do you recall what the intention of this was? What would two equally sized towns be needed for?

**Comment by Cervator** [comment]
I think this might have belonged to an early era Light & Shadow mode the intent of which was a bigger battleground with two entire cities facing each other. It was kinda-sorta implemented by allowing Cities to generate along a mirror line in the world, even if that generated _a lot more_ than just two cities. You'd still be able to find exact copies of two cities if you looked along the line. I wouldn't be surprised if that still exists, works, or is even active today, has just been an age since it was an active topic.

While I'd like to get back to the bigger-world version of LaS that's more of an "arc" board to serve as a backlog for things we _could_ do for LaS, that's pretty distinct from this ole issue which I'll close as done long ago :-)
